### ISSUE TITLE
Select box text is white-on-white on Rotten Tomatoes

### ISSUE THREAD

**Issue by evaryont** [RuudBurger/CouchPotatoExtension#10]
FF 35.0.1, Windows 8.1

![rotten_tomatoes_white_on_white_select](https://cloud.githubusercontent.com/assets/14547/6309925/18a3f4aa-b90f-11e4-8bdb-4a5fbe1ae37e.png)

The text is white because the parent element (`.cp__popup_info`) has `color: #fff` while RT's CSS has a global rule:

```css
button, input, optgroup, select, textarea {
    font: inherit;
    margin: 0px;
    color: inherit;
}
```

This causes the select box to have a white text color, on the default white background. Specifying a color for the element fixes it.
